# Generated by Django 2.1.7 on 2019-04-29 15:20

import catalog.items
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=catalog.items.ThumbnailImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
