# Generated by Django 2.1.7 on 2019-04-30 14:32

import catalog.items
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=catalog.items.ThumbnailImageField(upload_to='media/photos'),
        ),
    ]
