# Generated by Django 2.1.7 on 2019-04-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190430_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='filename'),
        ),
    ]
